services:
  - type: web
    name: vigilx-drowsiness
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
     - key: ALERT_PHONE_NUMBERS
        sync: false
      - key: PORT
        value: 10000
